august-thirty-first/backend

- .gitmodules
> feat: add submodule for env

- .gitignore
- #이슈번호
<br><br>
git ignore ** 추가하여 dist와 node_module 추적 끊었습니다
<br><br>
<br><br>
> git ignore ** 추가하여 dist와 node_module 추적 끊었습니다

- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/app.module.ts
- nestjs/src/auth/auth.controller.spec.ts
- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.module.ts
- nestjs/src/auth/auth.service.spec.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/user.dto.ts
- nestjs/src/auth/entities/User.entity.ts
- nestjs/src/auth/user.repository.ts
- nestjs/src/configs/typeorm.config.ts
- nestjs/src/main.ts
- nestjs/src/passports/fortytwo.strategy.ts
- nestjs/src/passports/jwt.strategy.ts
- nestjs/src/passports/passports.module.ts
- nestjs/src/passports/tempJwt.strategy.ts
- nestjs/src/temp-jwt/temp-jwt.module.ts
- #이슈번호
#11 
OAuth와 JWT토큰 발급을 위한 작업 및 환경변수 적용
<br><br>
Passports 디렉토리 만들어서 42토큰과 JWT토큰 발급을 위한 환경 처리  
package.json에 passport와 typeorm 의존성 추가  
User테이블 Entity로 DB생성 및 연결 테스트 완료
Auth에서 42로그인 후 리다이렉션 되는 URL에서 accessToken발급 확인 완료 및 최초 회원가입 구현 사전작업 완료
<br><br>
<br><br>
> Feat o auth backend 기능 추가

- nestjs/src/auth/auth.controller.ts
- #이슈번호
- #19 
- backend에서 API_KEY와 REDIRECT 주소를 확인해서 oauth 주소를 redirect 시켜주게 함
<br><br>
- auth controller에 api 하나 추가
<br><br>
- https://github.com/august-thirty-first/frontend/pull/16
<br><br>
> [feat] : redirect api 추가

- nestjs/src/auth/auth.controller.ts
- #20 
- 응답 메시지를 못받는 버그를 수정함.
<br><br>
- controller에서 send()메서드를 사용하여 응답 메시지를 보냄
<br><br>
<br><br>
> [bug] : response 메시지 send 해주어 pending 해결

- nestjs/src/auth/auth.controller.ts
- #
- hotfix 에러 처리
<br><br>
<br><br>
<br><br>
> [hotfix]: Update auth.controller.ts

- Makefile
- docker/docker-compose-test.yml
- docker/docker-compose.yml
- docker/nestjs/package-lock.json
- docker/test/Dockerfile
- docker/test/script.sh
- nestjs/package.json
- #27 
- Makefile 생성
- docker/docker-compose-test.yml 추가
- package.json 수정
<br><br>
위와 동일
<br><br>
<br><br>
> [chore]: Infra ci 테스트환경구성

- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/main.ts
- #31 
- main.ts에 global-pipe를 설정해서 Dto를 받는 controller에서 validation 처리를 함
<br><br>
- package.json에 class-transformer 추가
- main.ts에 app.useGlobalPipes 추가
<br><br>
- [auto-validation](https://docs.nestjs.com/techniques/validation#auto-validation)
<br><br>
> Refactor] 31 global-pipe-validation 설정하기

- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/checkNickname.dto.ts
- nestjs/src/auth/dto/userCreate.dto.ts
- nestjs/src/auth/interfaces/checkDuplicatedNicknameResponse.interface.ts
- nestjs/src/auth/user.repository.ts
- #35 
- 회원가입 실패시 사진 삭제 처리
- controller 타입 설정
<br><br>
<br><br>
<br><br>
> [refactor]: 회원가입 예외 처리 및 refactor

- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/checkNickname.dto.ts
- nestjs/src/auth/interfaces/checkDuplicatedNicknameResponse.interface.ts
- nestjs/src/auth/user.repository.ts
- nestjs/src/filter/interface/unauthorized.interface.ts
- nestjs/src/filter/oauth-exception.filter.ts
- nestjs/src/filter/unauthorized-exception.filter.ts
- #34 
- ExceptionFilter 추가 및 Controller method에 설정
<br><br>
- ExceptionFilter에서 jwt token을 삭제 시켜줌
- OAuthExceptionFilter 추가
<br><br>
<br><br>
> [feat] ExceptionFilter 추가

- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/app.module.ts
- nestjs/src/socket/game/game.gateway.spec.ts
- nestjs/src/socket/game/game.gateway.ts
- nestjs/src/socket/game/game.module.ts
- nestjs/src/socket/home/home.gateway.spec.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/home.module.ts
- #이슈번호
#40 
소켓 게이트웨이 만들기
<br><br>
game, home게이트웨이를 따로 만들고 네임스페이스단위로 나눠줬습니다.
<br><br>
<br><br>
> Feat 소켓 게이트웨이 만들기

- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/otpLogin.dto.ts
- #24 
- OTP 로그인 기능 추가
<br><br>
- 로그인시에 otp_key가 존재하는지 확인하여, otp Page로 redirect 처리 되게 하였습니다.
- OTP 인증 완료 후에, 정상 토큰을 발급하도록 해주었습니다.
<br><br>
<br><br>
> Feat 24 otp 2차 인증 구현

- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/app.module.ts
- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/otpLogin.dto.ts
- nestjs/src/profile/dto/myInfo.dto.ts
- nestjs/src/profile/dto/otpResponseDto.dto.ts
- nestjs/src/profile/dto/otpSetup.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/dto/userUpdate.dto.ts
- nestjs/src/profile/profile.controller.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- #39 
- qrcode, speakeasy library 추가
- profile API 추가
<br><br>
- 내 정보 확인 API 추가 (GET, me)
- user 검색 API 추가 (GET, user)
- profile에서 닉네임 확인 API 추가(POST, nickname)
- 정보 변경 API 추가 (PATCH, edit)
- OTP 정보 API 추가 (GET, otp)
- OTP 설정 API 추가 (PATCH, otp)
- OTP 삭제 API 추가 (DELETE, otp)
<br><br>
<br><br>
> Feat 39 profile 기능 구현

- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/app.module.ts
- nestjs/src/auth/auth.controller.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/dto/otpLogin.dto.ts
- nestjs/src/profile/dto/myInfo.dto.ts
- nestjs/src/profile/dto/otpResponseDto.dto.ts
- nestjs/src/profile/dto/otpSetup.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/dto/userUpdate.dto.ts
- nestjs/src/profile/profile.controller.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- #44 
- ServeStaticModule를 추가해서, Images 폴더의 이미지 파일들을 제공
<br><br>
- 라이브러리 추가
- app.module.ts 파일 수정
<br><br>
- [nest.js serve static](https://docs.nestjs.com/recipes/serve-static#installation)
<br><br>
> Feat 44 이미지 파일 백엔드 url로 제공

- nestjs/src/auth/dto/checkNickname.dto.ts
- nestjs/src/auth/dto/userCreate.dto.ts
- #50 
- Dto transform 처리시 발생하는 bug 처리
<br><br>
- 옵셔널 체이닝으로 value값 확인하였음
<br><br>
<br><br>
> [bug] dto transform bug fix

- nestjs/src/passports/jwt.strategy.ts
- nestjs/src/passports/passports.module.ts
- #48 
- passport jwt에서 validate 처리를 하는걸 건의
<br><br>
- jwt validate 함수에서 User 검색을 한번 처리해주기
<br><br>
<br><br>
> [refactor] passport jwt user 검증

- docker/nestjs/Dockerfile
- nestjs/nest-cli.json
- nestjs/package-lock.json
- nestjs/package.json
- nestjs/src/app.module.ts
- nestjs/src/chat/chat.controller.spec.ts
- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.module.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chat.service.spec.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/chat/dto/chat.dto.ts
- nestjs/src/chat/dto/chatCreate.dto.ts
- nestjs/src/chat/dto/chatParticipant.dto.ts
- nestjs/src/chat/dto/chatParticipantCreate.dto.ts
- nestjs/src/chat/entities/chat.entity.ts
- nestjs/src/chat/entities/chatParticipant.entity.ts
- nestjs/src/chat/enum/chat.status.enum.ts
- nestjs/src/chat/enum/chatParticipant.status.enum.ts
- nestjs/src/main.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/home.module.ts
- #이슈번호
#
프론트엔드에서 필요할만한 chat관련 api구현
<br><br>
- 특정 user가 속해있는 chatRoom만 가져오는 API
- chatParticipant의 status, ban 상태를 바꾸는 API
- 채팅방 나갈때 쓰는 chatParticipant Delete API
<br><br>
이슈를 파고 브랜치를 좀더 나눠서 했어야했는데 중구난방으로 코드를 짜버렸네요...ㅜㅜ
<br><br>
> Feat 채팅 기능 구현

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/chat/dto/chatParticipant.dto.ts
- nestjs/src/chat/dto/chatParticipantCreate.dto.ts
- nestjs/src/chat/entities/chatParticipant.entity.ts
- nestjs/src/chat/enum/chatParticipant.authority.enum.ts
- nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#62 
채팅방 생성과 참여시 authoirty 설정
<br><br>
프론트에서 따로 boss, admin, normal인지 알려주지 않고
- 채팅방 생성시에는 boss
- 채팅방 참가시에는 normal
- normal <-> admin 권한 변경 요청시 boss, admin이 요청한것이 맞는지 검증
- ban 요청시 boss, admin이 요청한것이 맞는지 검증
<br><br>
<br><br>
> Feat 채팅방 생성 및 참가 로직 변경

- nestjs/src/chat/chat.service.ts
- #이슈번호
#69 
Chat의 status에 따른 password 존재여부 처리
<br><br>
- public, private이고 password가 null이 아니면 throw error
- protected이고 password가 null이면 throw error
- 채팅방 생성, 수정, 참여에 위 두개 로직 추가함
<br><br>
checkChatStatusAndPassword 함수 로직에 모든게 다 있습니다.
<br><br>
> [Fix]: Chat의 Status에 따른 password의 옳바른 처리

- nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#73 
채팅방을 삭제할 때 소켓에도 이벤트 보내주기
<br><br>
home.gateway.ts 파일에서 deleteRoom 이벤트 추가
<br><br>
<br><br>
> [Feat]: 채팅방이 삭제되었을때 소켓 이벤트 추가

- nestjs/src/socket/game/class/ball.ts
- nestjs/src/socket/game/class/bar.ts
- nestjs/src/socket/game/class/gamePlayer.ts
- nestjs/src/socket/game/class/positon.ts
- nestjs/src/socket/game/class/renderInfo.ts
- nestjs/src/socket/game/class/velocity.ts
- nestjs/src/socket/game/enum/initStatus.enum.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/utils/getRandomNumberRange.ts
- #77 
ball 객체의 초기 속도 랜덤 선정 bar 초기 속도 설정 하기
<br><br>
- velocity class 추가
- velocity가 필요한 ball, bar 객체에 프로퍼티, 관련 메소드 추가
- 특정 숫자 범위안에서 랜덤으로 숫자를 반환하는 함수 구현 -> 해당 함수로 ball의 초기 속도 설정
<br><br>
<br><br>
> ball 객체의 초기 속도 랜덤 선정 bar 초기 속도 설정 하기

- nestjs/src/app.module.ts
- nestjs/src/friend/dto/friendCommon.dto.ts
- nestjs/src/friend/dto/friendCommonRequestBody.dto.ts
- nestjs/src/friend/dto/friendGetResponse.dto.ts
- nestjs/src/friend/dto/friendRequesting.dto.ts
- nestjs/src/friend/entities/FriendRequesting.entity.ts
- nestjs/src/friend/entities/Friends.entity.ts
- nestjs/src/friend/friend.controller.ts
- nestjs/src/friend/friend.module.ts
- nestjs/src/friend/friend.service.ts
- nestjs/src/friend/friendRequesting.repository.ts
- nestjs/src/friend/friends.repository.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/profile.controller.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- #55 
- 친구 기능에 필요한 내용이 추가되었습니다.
<br><br>
- [feat] Friends Entity
- [feat] FriendRequesting Entity 생성
- [refactor] profile 검색시 친구 관계에 대해서도 response data가 추가되었습니다.
구현한 API
- 친구 요청 (POST /friend/request)
- 친구 요청 취소 (PATCH /friend/cancel)
- 친구 요청 거절 (PATCH /friend/reject)
- 친구 요청 승인 (PATCH /friend/approve)
- 친구 삭제 (DELETE /friend)
- 친구 목록 조회 (GET /friend)
<br><br>
<br><br>
> Feat 55 친구 기능 만들기

- nestjs/src/socket/game/enum/initStatus.enum.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- #88 
클라이언트에서 keyDown 이벤트 들어왔을 때 bar position 계산 로직 구현
<br><br>
- 이벤트에 따른 위치 계산
- bar가 제한 범위 밖으로 넘어가지 못하도록 움직임 구속
<br><br>
<br><br>
> keydown 이벤트 처리 로직 구현

- nestjs/src/socket/game/class/ball.ts
- nestjs/src/socket/game/class/bar.ts
- nestjs/src/socket/game/class/gamePlayer.ts
- nestjs/src/socket/game/class/renderInfo.ts
- nestjs/src/socket/game/enum/initStatus.enum.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #93 
Ball과 Bar를 그리기 위해 모양을 나타내는 프로퍼티 추가
map 난이도에 따라 bar와 ball의 크기를 조정할
<br><br>
- ball
- radius 추가
- bar
- width, length 추가
- 그려지는 시작점이 사각형의 왼쪽 위 점이기 때문에 position을 해당 위치로 생각하고 초기값 위치 계산법 변경
<br><br>
<br><br>
> ball 객체와 bar 객체의 모양을 표현할 수 있는 프로퍼티 추가

- nestjs/src/socket/home/home.gateway.ts
- #95 
- 토큰 만료시에 서버에서도 자동적으로 소켓을 끊는 처리가 필요함
<br><br>
- 소켓 연결시 토큰의 만료 시간을 확인해서, 실행되는 setTimeout 설정
<br><br>
<br><br>
> [bug] 토큰 만료시 소켓 종료 예약 함수 설정

- nestjs/src/socket/game/class/bar.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #99 
ball 움직임 및 충돌 구현
<br><br>
- ball 속도에 따른 위치 계산
- ball 벽 및 bar 충돌 후 속도 변화 계산
- 게임 스코어 업데이트 구현
<br><br>
<br><br>
> ball 움직임 및 충돌 구현

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/chat/entities/chat.entity.ts
- nestjs/src/socket/home/dto/message.dto.ts
- nestjs/src/socket/home/dto/roomId.dto.ts
- nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#86 
Chat 기능 관련 크고작은 에러를 테스트를 통해 처리를 했습니다.
<br><br>
- chat.service.ts파일 리팩터링
- ChatRoom 입장시 비밀번호 검증 및 ban(permission) 확인 API추가
<br><br>
<br><br>
> Feat chatservicets파일 리팩터링

- nestjs/src/socket/game/class/ball.ts
- nestjs/src/socket/game/enum/initStatus.enum.ts
- nestjs/src/socket/game/utils/getRandomNumberRange.ts
- #105 
공 속도 초기화시 랜덤으로 너무 느린 속도까지 선택될 수 있는 문제가 있었음
<br><br>
- 양 수 범위를 넣고 랜덤으로 범위 사이의 값을 선택 한뒤  랜덤으로 양수 음수를 선택할 수 있도록 구현함
<br><br>
<br><br>
> 공 속도가 너무 느리게 초기화 되는 문제 해결

- nestjs/src/socket/home/home.gateway.ts
- close #112
- 토큰 만료, multipleConnect 이벤트 보내는 걸로 수정
<br><br>
- expired, multipleConnect 이벤트 추가
<br><br>
<br><br>
> [fix] multipleConnect, expired 이벤트 추가

- nestjs/src/profile/profile.controller.ts
- #94 
- OTP 설정 및 해제시에 DB 작업을 기다리지 않아서, front단에서 view적으로 문제가 있어서 수정
<br><br>
<br><br>
<br><br>
> [fix] db 처리를 await하지 않는 오류 해결

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/chat/dto/chatParticipantAuthority.dto.ts
- #이슈번호
close #119 
chat 로직 추가에 따른 리팩터링
<br><br>
- repository단에서 쿼리를 실행하게 변경
- chat_room_id에 따른 참가자 유저 정보조회 API에서 은닉정보 제외
- 가독성을 위한 함수 위치와 함수명 변경
<br><br>
<br><br>
> Feat 119 chat 로직 추가에 따른 리팩터링

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/dto/chatParticipantAuthority.dto.ts
- #124 
파라미터와 body 혼용부분 리팩터링
<br><br>
- body로 데이터를 받게 변경
<br><br>
- switchAuthority 함수 확인요망
<br><br>
> [Fix]: 파라미터와 body 혼용부분 리팩터링

- nestjs/src/filter/unauthorized-exception.filter.ts
- nestjs/src/socket/game/class/game.ts
- nestjs/src/socket/game/class/gamePlayer.ts
- nestjs/src/socket/game/class/matchHistory.ts
- nestjs/src/socket/game/class/user.ts
- nestjs/src/socket/game/dto/createGameHistory.dto.ts
- nestjs/src/socket/game/entities/gameHistory.entity.ts
- nestjs/src/socket/game/enum/gameStatus.enum.ts
- nestjs/src/socket/game/enum/gameType.enum.ts
- nestjs/src/socket/game/gameHistory.repository.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.module.ts
- nestjs/src/socket/game/gameSocket.service.ts
- close #101 
특정 스코어에 도달 했을 때 게임 종료 및 데이터 베이스 업데이트
<br><br>
- 상세 작업내용 이슈 확인 부탁드립니다.
<br><br>
<br><br>
> 게임 종료 및 종료 이후 이벤트 및 자원 관리

- nestjs/src/socket/game/gameConnection.service.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.module.ts
- close #139
게임 접속 상태를 관리하는 별도의 서비스 만들기
<br><br>
- gameConnectionService를 만들고 다른 모듈에서 쓸 수 있도록 export 함
<br><br>
<br><br>
> 게임 접속 상태를 관리하는 별도의 서비스 만들기

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- #이슈번호
close #133 
private 채팅방 구현
<br><br>
- 전체 채팅방 조회 API를 오픈 채팅방 조회 API로 변경
- Private방도 Protected방처럼 비밀번호 여부를 검사
- Private방에는 join이 되지 않도록 설정
<br><br>
<br><br>
> [Feat]: private 채팅방 구현

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/home/connection.service.ts
- nestjs/src/socket/home/dto/directMessage.dto.ts
- nestjs/src/socket/home/dto/skill.dto.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/message.service.ts
- #이슈번호
close #144  
dm기능 추가
<br><br>
- directMessage 이벤트 생성
- payload로 targetUserId를 받아오도록
- directMessage시에 다른 room에서 나가주도록 함
<br><br>
- 프론트앤드에서 enterRoom 이벤트가 두번씩 오는 문제 발견
<br><br>
> Feat dm 기능 추가

- nestjs/src/achievement/dto/getAchievement.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- #151 
- achievement를 Profile API에서 가져올 수 있게 수정
<br><br>
- getAchievementDto 추가 및 searchUserDto 수정
- friend_status 를 가져오는 코드를 함수로 나눠서 refactor
- user의 achivement를 가져오는 함수인 getProfileUserAchievement 추가
<br><br>
<br><br>
> Feat 151 achievement profile 검색

- nestjs/src/friend/friendRequesting.repository.ts
- await 하지 않으니, catch 문에서 잡지 못하는 issue 발생
<br><br>
- await 처리해줬습니다.
<br><br>
- 다른곳에서도 이런 코드가 있던데 좀 논의 해봐야될듯 합니다.
<br><br>
> [fix] friend request save시에 await 처리

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/home/blackList.repository.ts
- nestjs/src/socket/home/dto/userId.dto.ts
- nestjs/src/socket/home/entities/blackList.entity.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/home.module.ts
- nestjs/src/socket/home/message.service.ts
함수명변경
<br><br>
- 지난 pull request에서 getOpenChat함수명 변경이 controller에서는 반영이 안되있는 점 발견하여 수정함
<br><br>
<br><br>
> Hotfix 함수명변경

- nestjs/src/filter/unauthorized-exception.filter.ts
- nestjs/src/friend/friend.module.ts
- nestjs/src/friend/friend.service.ts
- nestjs/src/socket/game/class/game.ts
- nestjs/src/socket/game/class/gamePlayer.ts
- nestjs/src/socket/game/class/matchHistory.ts
- nestjs/src/socket/game/class/user.ts
- nestjs/src/socket/game/dto/createGameHistory.dto.ts
- nestjs/src/socket/game/entities/gameHistory.entity.ts
- nestjs/src/socket/game/enum/gameStatus.enum.ts
- nestjs/src/socket/game/enum/gameType.enum.ts
- nestjs/src/socket/game/gameConnection.service.ts
- nestjs/src/socket/game/gameHistory.repository.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.module.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #160
- 친구 상태에서 게임중을 추가했습니다.
- 현 dev-game을 merge 했습니다.
<br><br>
- gameSocketModule에서의 gameConnectionService를 inject해서 해당 유저 찾기
<br><br>
- 맨 마지막 commit만 보시면 됩니다
<br><br>
> 160 친구 목록에서 유저 게임 상태 체크하기

- nestjs/src/socket/game/enum/userStatus.enum.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #113 
게임 방에 참가 하지 않은 유저가 게임 관련 url로 직접 접근하는 것을 막는 검증 로직 구현
<br><br>
- /game , /game/option 페이지 직접 접근 막는 로직 작성
- user 상태 상세하게 분리
- 각종 버그 수정 ( 커밋 참고)
<br><br>
<br><br>
> game url 직접 접근 막는 로직 작성

- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.service.ts
- close #158 
- 유저 아이디가 제대로 저장되지 않는 버그 수정
<br><br>
- gamePlayer 초기화시 잘못된 인자 전달하고 있는 것을 발견하여 수정
<br><br>
<br><br>
> 게임 히스토리 저장 버그

- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/home/connection.service.ts
- nestjs/src/socket/home/dto/directMessage.dto.ts
- nestjs/src/socket/home/dto/message.dto.ts
- nestjs/src/socket/home/dto/roomId.dto.ts
- nestjs/src/socket/home/dto/skill.dto.ts
- nestjs/src/socket/home/dto/userId.dto.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/message.service.ts
mute kick 오류수정
<br><br>
- 모든 Id는 number로 수신하도록 통일
- DTO에 validator 설정
- (중요) Map에 key를 배열에서 string으로 변경
<br><br>
- TypeScript, JavaScript에서는 배열도 하나의 객체로 구분한다. 따라서 [1, 2] === [1, 2]는 언제나 false이다
<br><br>
> Hotfix mute kick 오류수정

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/home/connection.service.ts
- nestjs/src/socket/home/dto/directMessage.dto.ts
- nestjs/src/socket/home/dto/message.dto.ts
- nestjs/src/socket/home/dto/roomId.dto.ts
- nestjs/src/socket/home/dto/skill.dto.ts
- nestjs/src/socket/home/dto/userId.dto.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/message.service.ts
- #이슈번호
#163 
API생성 및 수정
<br><br>
```
기존 AP I변경
Get /api/chat/participant -> participation
Post /api/chat/participant -> register
Post /api/chat/participant/permission -> enter
Get /api/chat/participant/:chat_room_id -> api/chatallParticipant/:chat_room_id
```
```
채팅방 내의 내 정보를 가져오는 API 생성
Get /api/chat/allParticipant/:chat_room_id
```
<br><br>
맨 밑 두개 커밋만 보시면 됩니다.
<br><br>
> Feat 채팅방에 참여했을 때 내 정보를 가져오는 api

- nestjs/src/chat/chat.service.ts
Hotfix boss가 ban이되는현상 fix
<br><br>
<br><br>
> [Fix]: boss가 ban이 되는 현상 Fix

- nestjs/src/chat/chat.service.ts
- nestjs/src/socket/home/blackList.repository.ts
blackList를 가져오는 쿼리에서 to와 from을 가져오지 못하는 오류 수정
<br><br>
<br><br>
> Hotfix black list의 쿼리 수정

- nestjs/src/socket/game/class/matchHistory.ts
- nestjs/src/socket/game/dto/createLadder.dto.ts
- nestjs/src/socket/game/entities/ladder.entity.ts
- nestjs/src/socket/game/enum/gameStatus.enum.ts
- nestjs/src/socket/game/gameHistory.repository.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.module.ts
- nestjs/src/socket/game/gameSocket.service.ts
- nestjs/src/socket/game/ladder.repository.ts
- #165 
래더점수 엔티티 생성 및 래더 점수 계산 로직 구현
<br><br>
- ladder 엔티티 생성
- ladder 엔티티 업데이트 로직 구현
<br><br>
<br><br>
> 래더점수 엔티티 생성 및 래더 점수 계산 로직 구현

- nestjs/src/profile/dto/gameData.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- nestjs/src/socket/game/dto/getGameHistory.dto.ts
- nestjs/src/socket/game/gameHistory.repository.ts
- #171 
- GameHistory 결과 출력 (최근 10개만)
<br><br>
- GameHistoryRepository 수정
- 관련 DTO 파일 추가
- 프로필 검색시 로직 추가
<br><br>
<br><br>
> 171 profile에서 db game history 보내주기

- nestjs/src/profile/dto/gameData.dto.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- nestjs/src/socket/game/entities/ladder.entity.ts
- nestjs/src/socket/game/ladder.repository.ts
- #180 
- 프로필 API에서 레더 점수 추가
<br><br>
- ladder entity 수정
- ladder repository에 점수 가져오기 함수 추가
- gameDto에 ladder 변수 추가
- 프로필 검색시 ladder 점수도 검색해서 response에 추가
<br><br>
<br><br>
> Feat 180 레더 점수 출력하기

- nestjs/src/auth/auth.service.ts
- nestjs/src/filter/oauth-exception.filter.ts
- nestjs/src/main.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/home/home.gateway.ts
- #185
- localhost 코드를 process.env파일에서 참조하게 변경하였습니다.
<br><br>
<br><br>
- .env 파일 update 하셔야합니다!
<br><br>
> [feat] localhost -> env 참조

- nestjs/src/socket/home/home.gateway.ts
- #193 
- DM 전송 관련 bug 수정
<br><br>
- offline 유저한테 메세지 보낼시 undefined 에러 수정
=> message event로 offline user 표시
- dm 보내고 leaveRoom 로직 제거
=> 기존 채팅방에서 나갈 필요가 없음
<br><br>
<br><br>
> [bug] DM 전송 버그 픽스

- nestjs/src/socket/game/gameSocket.gateway.ts
- #181 
게임소켓에서 오류가 나는 문제 해결
<br><br>
- undefined된 값을 읽을 일이 없도록 예외처리
- shift() 메소드 사용하여 joinqueue 리팩토링
<br><br>
<br><br>
> 게임소켓에서 오류가 나는 문제

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.module.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/interfaces/ChatParticipantWithBlackList.interface.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/message.service.ts
채팅방번호 대신 이름노출을 위한 API 생성
<br><br>
<br><br>
<br><br>
> Hotfix 채팅방번호 대신 이름노출

- nestjs/src/chat/chat.controller.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chat.service.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/chat/entities/chat.entity.ts
- nestjs/src/chat/entities/chatParticipant.entity.ts
- nestjs/src/chat/interfaces/ChatParticipantWithBlackList.interface.ts
- nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#210 
타입 지정을 안하거나 or( | ) 로 묶어야 하는 부분 수정
<br><br>
<br><br>
<br><br>
> Feat 채팅 쪽 strict 옵션 주고 타입 설정해주기

- nestjs/src/chat/chat.service.ts
- #이슈번호
#209 
leaveRoom 함수의 에러메시지 변경
<br><br>
<br><br>
<br><br>
> [Fix]: 채팅방 삭제시 에러메시지 변경

- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/home/blackList.repository.ts
- #이슈번호
#208 
get 쿼리에 order 지정
<br><br>
- chat,  chatParticipant, blackList 테이블
<br><br>
<br><br>
> Feat 쿼리 정렬 필요

- nestjs/src/achievement/userAchievement.repository.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/entities/User.entity.ts
- nestjs/src/auth/user.repository.ts
- nestjs/src/auth/utils/crypto.service.ts
- nestjs/src/friend/dto/friendGetResponse.dto.ts
- nestjs/src/friend/friend.service.ts
- nestjs/src/main.ts
- nestjs/src/passports/jwt.strategy.ts
- nestjs/src/profile/dto/gameData.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/profile.controller.ts
- nestjs/src/profile/profile.service.ts
- nestjs/src/socket/game/dto/getGameHistory.dto.ts
- #205 
- typescript의 strict 옵션을 사용해서 type check를 진행해서 fix
<br><br>
<br><br>
tsconfig에 다음 코드로 수정해주시면 됩니다.
```json
{
"compilerOptions": {
"strict": true,
"strictPropertyInitialization": false,
"module": "commonjs",
"declaration": true,
"removeComments": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"allowSyntheticDefaultImports": true,
"target": "ES2021",
"sourceMap": true,
"outDir": "./dist",
"baseUrl": "./",
"incremental": true,
"strictNullChecks": true,
"noImplicitAny": false,
"strictBindCallApply": false,
"skipLibCheck": true,
"forceConsistentCasingInFileNames": false,
"noFallthroughCasesInSwitch": false
}
}
```
<br><br>
> [refactor] strict type check 적용

- nestjs/src/achievement/userAchievement.repository.ts
- nestjs/src/auth/auth.service.ts
- nestjs/src/auth/entities/User.entity.ts
- nestjs/src/auth/user.repository.ts
- nestjs/src/auth/utils/crypto.service.ts
- nestjs/src/filter/oauth-exception.filter.ts
- nestjs/src/friend/dto/friendGetResponse.dto.ts
- nestjs/src/friend/friend.service.ts
- nestjs/src/main.ts
- nestjs/src/passports/jwt.strategy.ts
- nestjs/src/profile/dto/gameData.dto.ts
- nestjs/src/profile/dto/searchUser.dto.ts
- nestjs/src/profile/profile.controller.ts
- nestjs/src/profile/profile.module.ts
- nestjs/src/profile/profile.service.ts
- nestjs/src/socket/game/dto/getGameHistory.dto.ts
- nestjs/src/socket/game/entities/ladder.entity.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/ladder.repository.ts
- nestjs/src/socket/home/home.gateway.ts
- #이슈번호
<br><br>
<br><br>
<br><br>
> Dev user 2.0 PR

- nestjs/src/socket/home/home.gateway.ts
- 안쓰는 주석과 인자를 삭제했습니다.
<br><br>
> Hotfix chat 주석삭제

- nestjs/src/app.module.ts
- nestjs/src/auth/auth.module.ts
- nestjs/src/friend/friend.module.ts
- nestjs/src/socket/connection.module.ts
- nestjs/src/socket/game/gameSocket.module.ts
- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/home.module.ts
- #218 
- 게임 초대시 예외 처리
<br><br>
<br><br>
<br><br>
> Bug 218 게임중인 사람 게임 초대 불가

- nestjs/src/socket/game/enum/initStatus.enum.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #214 
게임 플레이 관련 옵션 값 수정
<br><br>
- 바 길이 및 두께, 공 반지름 수정
- 공이 바에 충돌했을 때 속도 조정
<br><br>
<br><br>
> 게임 플레이 관련 옵션 값 수정

- nestjs/src/auth/auth.controller.ts
- nestjs/src/friend/dto/friendRequestingAlarms.dto.ts
- #225 
<br><br>
<br><br>
<br><br>
> [refactor] strict 에러 처리

- nestjs/src/socket/home/home.gateway.ts
- nestjs/src/socket/home/message.service.ts
- chat 부분 strict 옵션 적용했습니다.
<br><br>
<br><br>
> [Fix]: strict 옵션 적용

- nestjs/src/socket/game/class/game.ts
- nestjs/src/socket/game/gameConnection.service.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/gameSocket.service.ts
- #224 
game 관련 서비스 strict 모드로 컴파일하고 수정
<br><br>
<br><br>
<br><br>
> game 관련 서비스 strict 모드로 컴파일하고 수정

- nestjs/src/socket/home/home.gateway.ts
<br><br>
- DM 전송시 오프라인 유저 예외 처리
<br><br>
<br><br>
> [feat] DM 오프라인시 예외 처리

- nestjs/src/auth/user.repository.ts
- nestjs/src/chat/chat.respository.ts
- nestjs/src/chat/chatParticipant.repository.ts
- nestjs/src/socket/game/gameHistory.repository.ts
- nestjs/src/socket/game/gameSocket.gateway.ts
- nestjs/src/socket/game/ladder.repository.ts
- nestjs/src/socket/home/home.gateway.ts
- #239 
consolelog 주석처리
<br><br>
- consolelog 주석처리
<br><br>
<br><br>
> consolelog 주석처리
