nestjs/src/socket/game/game.gateway.ts
- #49 
- 래더게임의 대기 큐 생성 및 매칭 시스템 구현
<br><br>
- joinQueue 이벤트 발생시 대기 큐에 소켓을 넣어서 매칭을 대기함
- room 번호는 소켓의 default room 번호인 소켓 아이디를 사용함
- 소켓 연결 끊어 졌을때 큐에서 제거함
<br><br>
<br><br>
=> 래더 게임을 위한 대기큐 만들기

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.service.ts, nestjs/src/chat/chatParticipant.repository.ts, nestjs/src/chat/dto/chatJoin.dto.ts, nestjs/src/chat/dto/chatParticipant.dto.ts, nestjs/src/chat/dto/chatParticipantCreate.dto.ts, nestjs/src/chat/entities/chatParticipant.entity.ts, nestjs/src/chat/enum/chatParticipant.authority.enum.ts, nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#60 
protected, public 채팅방 입장 로직 추가
<br><br>
- protected 채팅방에 참여할때는 데이터베이스에 해시되어 저장되어있는 비밀번호와 compare하여 참여 여부를 결정함
- joinAlreadyExistChat, joinNotExistChat 함수 이용하여 joinChat 함수 리팩터링
<br><br>
- ChatJoinDto 추가하였습니다.
- service단에서 함수를 쪼개고있는데 가독성 좋은지 판단좀 부탁드립니다. 처음 해보는거라서 이런식으로 나누는게 맞나 싶네요
<br><br>
=> Feat protected 채팅방에 참여할때 비밀번호 검증 기능 추가

nestjs/src/chat/chat.service.ts, nestjs/src/chat/entities/chat.entity.ts, nestjs/src/chat/entities/chatParticipant.entity.ts
- #이슈번호
#65 
chat테이블 삭제시 chatParticipant FK로 인한 오류 수정
<br><br>
- Chat Entity에서 OneToMany 데코레이터 추가 후 cascade: true 설정
- ChatParticipant Entity에서 ManyToOne 데코레이터에서 { onDelete: 'CASCADE' } 추가
<br><br>
- Chat, ChatParticipant table에 대한 무결성을 좀더 고려해봐야 할 것 같습니다
<br><br>
=> Feat chat테이블 delete query fail 오류

nestjs/src/chat/chat.service.ts, nestjs/src/socket/home/home.gateway.ts
비밀번호 null검증방식 변경
<br><br>
- 프론트앤드에서 null로 password를 넘기는게 불가능함으로 null이 아닌 trim함수를 통한 빈문자열로 null 판단
<br><br>
<br><br>
=> Hotfix 비밀번호 null검증방식 변경

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.service.ts
- #이슈번호
74
채팅방 참여 기능 수정 및 추가
<br><br>
- (GET) api/chat/participant/{user_id} 에서 {user_id} 빼고 토큰으로 확인하도록 변경
- 채팅방 참여자 목록을 반환하는 API추가 --> /api/chat/participant/{chat_room_id}
- API path: notban --> unban으로 변경
- 채팅방 참여자 삭제 API에 path로 participant/ 추가
<br><br>
<br><br>
=> [Feat]: 채팅방 참여 기능 수정및 추가

nestjs/src/chat/entities/chat.entity.ts
typeORM의 Column 데코레이터에서 select: false 처리를 통해 프론트앤드로 전송이 안되도록 변경
=> [Fix]: Password는 query select에서 제외

nestjs/src/auth/auth.module.ts, nestjs/src/auth/auth.service.ts, nestjs/src/filter/oauth-exception.filter.ts, nestjs/src/friend/dto/friendGetResponse.dto.ts, nestjs/src/friend/dto/friendRequestingAlarms.dto.ts, nestjs/src/friend/friend.controller.ts, nestjs/src/friend/friend.module.ts, nestjs/src/friend/friend.service.ts, nestjs/src/friend/friendRequesting.repository.ts, nestjs/src/friend/friends.repository.ts, nestjs/src/profile/dto/searchUser.dto.ts, nestjs/src/profile/profile.service.ts, nestjs/src/socket/home/connection.service.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/home.module.ts
- #79 
- 알람 서비스 처리 및 유저 상태 확인 처리 기능 추가
<br><br>
- SearchUserRequestStatus enum명에서 FriendRequestStatus로 좀 명확하게 이름을 변경했습니다.
- 다중 로그인 방지 처리를 하는 코드가 추가 되었습니다.
- Login시에 다중 로그인시 error 메세지를 추가하였습니다.
=> 기능 작동을 위해서 user에도 추가했습니다
- getFriend시에 친구의 상태를 socket map 에서 검색해서 online, offline을 return
=> 추후에 game status도 확인하여 게임중 상태도 표시할 예정
- /friend/alarms API 추가
=> 해당 user에 친구 요청 목록을 조회해서 가져오기
<br><br>
<br><br>
=> Feat 79 알림 서비스 처리 및 유저 상태 확인

nestjs/src/auth/auth.module.ts, nestjs/src/auth/auth.service.ts, nestjs/src/filter/oauth-exception.filter.ts, nestjs/src/socket/home/connection.service.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/home.module.ts
- #81 
- 다중 로그인 방지 처리를 하는 코드가 추가 되었습니다.
- Login시에 다중 로그인시 error 메세지를 추가하였습니다.
<br><br>
- 유저와 소켓 정보를 저장하는 ConnectionService 추가
- Oauth 로그인시에 error 메시지 수정
- 소켓 connect, disconnect 시에 ConnectionService에 있는 소켓 정보 제거
<br><br>
<br><br>
=> [feat]: 다중 로그인 방지 처리

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.service.ts, nestjs/src/chat/chatParticipant.repository.ts, nestjs/src/chat/dto/chatParticipantAuthority.dto.ts
- #이슈번호
close #117 
BOSS가 채팅방을 나갔을때에 대한 처리
<br><br>
- chatParticipant 테이블의 delete를 kick, leave 두가지 경우로 분리
- kick은 요청한 유저의 권한도 확인 (Boss or Admin)
- chatJoin함수에서 ban 권한을 확인하는 로직 삭제(임시 주석처리 추후 삭제예정)
<br><br>
<br><br>
=> [Feat]: BOSS가 방을 나갔을때 처리

nestjs/src/socket/home/home.gateway.ts
- #112 
- 다중 로그인 예외 처리
<br><br>
- timeout 설정을 하지 않으면, client의 event listener가 설정되기 전에 메세지가 전송될 수 있음. 이를 방지하기 위해 약 500ms 이후에 요청을 보내도록 설정
<br><br>
<br><br>
=> [fix] emit과 disconnect를 timeout 설정

nestjs/src/filter/unauthorized-exception.filter.ts
- #116
- UnauthorizedExceptionFilter 예외 처리
<br><br>
- UnauthorizedException을 return 해야 되는 상황이 존재할 수 있음. 예) 잘못된 패스워드 값 입력 등
- jwt 토큰 UnauthorizedException일때를 확인해서 clearCookie 처리
<br><br>
- unauthorizedException의 message 기본값은 'Unauthorized' 임.
- throw new unauthorizedException('에러 메세지') 시에 앞에 처럼 무조건 에러 메세지를 남겨야함
<br><br>
=> Hotfix 116 unauthorizedexceptionfilter 예외 처리

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.service.ts
- #이슈번호
#130 
채팅방 삭제 수정 API
<br><br>
- 채팅방 삭제API는 없앴음(boss가 나갈때만 채팅방이 삭제되게 하기 위해서
- 채팅방 수정 API호출시 호출한 유저의 권한 boss or admin 확인
<br><br>
<br><br>
=> [Fix]: 채팅방 수정, 삭제 API

nestjs/src/chat/chatParticipant.repository.ts, nestjs/src/socket/home/dto/mute.dto.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/home.module.ts, nestjs/src/socket/home/message.service.ts
- #이슈번호
#126 
채팅방 mute기능을 추가했습니다
<br><br>
- messageService.ts파일에서 Map자료구조로 mute상태 관리
- setTimeout 10초 후 Map자료구조에서 mute를 해제해줌
- mute를 명령한 사용자의 jwt를 확인하여 DB에서 boss or admin인지 권한을 확인
<br><br>
- handleConnection 함수에서 jwt를 받아오는 로직을 따로 messageService.ts파일로 뺐습니다.
- 지금은 10초 mute인데 협의 후 바꿀 수 있습니다.
<br><br>
=> Feat 126 mute기능 추가

nestjs/src/socket/game/gameSocket.gateway.ts, nestjs/src/socket/game/gameSocket.service.ts
- close #102 
게임 라이프 사이클 도중 유저 소켓이 끊겨 offline 상태가 되었을 때 로직 처리
<br><br>
- 상세 구현 내용 이슈에 적어 놓았습니다.
<br><br>
- 소켓이 끊겼을 때, 페이지 이동은 클라이언트에서 구현이 필요합니다.
- 뒤로가기 새로고침 버튼을 눌렀을 때 행동도 정해야 할 것 같습니다.
<br><br>
=> 게임의 전반 적인 라이프사이클 도중 유저가 offline이 되었을 때 로직 처리

nestjs/src/socket/game/enum/gameStatus.enum.ts, nestjs/src/socket/game/gameSocket.gateway.ts, nestjs/src/socket/game/gameSocket.service.ts
- close #147
gameOverInPlaying 이벤트를 보내는 순서가 잘못 되어 생긴 버그 수정
<br><br>
- game 상태에 gameOverInPlaying 상태를 추가
- 추가한 상태에 따라 이벤트가 전송될 수 있도록 수정
<br><br>
<br><br>
=> 게임 중 상대방 소켓이 끊겼을 때 이벤트 전송 순서에 따른 버그

nestjs/src/socket/home/connection.service.ts, nestjs/src/socket/home/dto/skill.dto.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/message.service.ts
- #이슈번호
close #136 
kick에 대해서만 소켓 이벤트 생성
<br><br>
- kick을 요청한 사람의 권한 확인 boss or admin
- kick을 당하는 사람을 권한 확인 no boss
- kick을 당하는 사람은 room leave 후 kick 이벤트 받음
- kick을 요청한 사람은 kick성공 여부를 kickReturnStatus이벤트로 받음
<br><br>
ban은 이 코드에서 처리 안하고 다른 이슈에서 해결할 예정
<br><br>
=> Feat ban과 kick에 대한 소켓 이벤트 생성

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.service.ts, nestjs/src/chat/chatParticipant.repository.ts, nestjs/src/socket/home/connection.service.ts, nestjs/src/socket/home/dto/skill.dto.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/message.service.ts
- #이슈번호
close #137 
ban이 된 사용자에 대한 권한 확인 및 소켓 처리
<br><br>
- 셀프 벤이 되는 현상 (boss가 boss밴 가능함)
- 채팅방 참여자를 가져오는 API가 ban인 사용자도 가져올 수 있는 현상
- ban이 된 사용자 권한을 제한해야 하는 API 검토
- ban이 되었을때 room에 join하고 있는 상태일 경우 소켓 이벤트 전송
<br><br>
커밋이 꼬여서 두개로 나뉘어져 갔습니다
<br><br>
=> Feat ban권한에 따른 기존 코드에서의 문제 발생

nestjs/src/chat/chat.respository.ts, nestjs/src/chat/chatParticipant.repository.ts, nestjs/src/socket/home/blackList.repository.ts, nestjs/src/socket/home/dto/userId.dto.ts, nestjs/src/socket/home/entities/blackList.entity.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/home.module.ts, nestjs/src/socket/home/message.service.ts
- #이슈번호
#148 
채팅방 차단 해제 api 생성
<br><br>
- BlackList 테이블 생성
- black list 설정 / 해제 시에 DB와 메모리에 동시에 수정을 함
- socket connection시에 DB에 접근하여 메모리에 정보를 가져옴
- DM 또는 채팅방에서 메시지 전송시 발신유저를 black list로 올린 수신유저에게는 메시지 전송이 되지 않음
<br><br>
- 앞으로 block / non block 이라는 용어 대신 set blackList / unset blacklist로 명명할 예정
- 발신 유저는 정상적으로 메시지를 보낼 수 있으므로 본인이 차단당한지 모름
- 과거 커밋부터 보시면 편하도록 해놨습니다
<br><br>
=> Feat 채팅방 차단 해제 api 생성

nestjs/src/auth/auth.module.ts, nestjs/src/auth/auth.service.ts, nestjs/src/auth/utils/crypto.service.ts, nestjs/src/profile/dto/otpSetup.dto.ts, nestjs/src/profile/profile.module.ts, nestjs/src/profile/profile.service.ts
- #157
- OTP_KEY를 DB에 바로 저장시키는 작업이 위험하다고 생각이 들어서, AES-256 방식으로 암호화 처리
<br><br>
- cryptoService 생성
=> encrypt, decrypt 함수 생성
- otp 설정시 encrypt
- otp 검증시 decrypt
<br><br>
- .env 파일 업데이트 하셔야 합니다
<br><br>
=> Feat 157 aes 256 otp key에 적용

nestjs/src/socket/home/generalGame.service.ts, nestjs/src/socket/home/home.module.ts
- #187 
일반 게임 매칭 로직 구현시 필요한 서비스 생성
<br><br>
- home 소켓을 다루는 곳에서 일반 게임 초대 정보를 저장하기 위해 map 자료구조를 가지고 있는 GeneralGameService 생성
<br><br>
<br><br>
=> generalgameservice 구현

nestjs/src/socket/home/generalGame.service.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/home.module.ts
- #189 
일반 게임 요청을 핸들링하는 subscriber 구현
<br><br>
- 게임 요청 현황을 generalgameservice에 map으로 저장
- fromUser에게 waitingPlayer 이벤트 전송
- toUser에게 selectJoin 이벤트 전송
<br><br>
<br><br>
=> requestGeneralGame 이벤트 핸들러 구현

nestjs/src/socket/game/gameConnection.service.ts, nestjs/src/socket/game/gameSocket.gateway.ts, nestjs/src/socket/game/gameSocket.module.ts
- #190 
GeneralGameApprove 이벤트 핸들러 구현
<br><br>
- toUser를 fromUser의 방으로 입장 시킨뒤에 게임 시작 로직을 시작한다(게임 옵션창 고르는 창으로 들어가기)
<br><br>
<br><br>
=> GeneralGameApprove 이벤트 핸들러 구현

nestjs/src/socket/game/gameSocket.gateway.ts, nestjs/src/socket/home/generalGame.service.ts
- #191 
general game 검증 로직 및 예외처리 구현
<br><br>
- 기존의 generalGameRefuse로직은 게임 소켓을 잘 끊어주는 것으로 대체
- 예외 시나리오에 대한 로직 구현
- A -> B 게임 요청
- A가 요청하고 어떤 사유던 게임 소켓 끊김
- B가 해당 요청을 수락함
- B에게 상대방이 요청을 취소했다는 사실을 알림 
- /game/general url로 직접 접근하지 못하도록 검증 로직 구현
<br><br>
<br><br>
=> general game 검증 로직 및 예외처리 구현

nestjs/src/chat/chat.controller.ts, nestjs/src/chat/chat.module.ts, nestjs/src/chat/chat.service.ts, nestjs/src/chat/interfaces/ChatParticipantWithBlackList.interface.ts, nestjs/src/socket/home/home.gateway.ts, nestjs/src/socket/home/message.service.ts
- #이슈번호
#197 
소켓을 이용해 채팅방 상태를 전송해야 하는 로직을 수정했습니다.
<br><br>
- unban 소켓 이벤트 추가하여 프론트에서 unban에 대한 메시지를 띄울 수 있게 하였습니다.
- 소켓이 연결되지 않을 때 ban이 되지 않는 문제를 해결했습니다.
- 채팅방 참여자 목록 반환 API에 blackList 속성을 boolean값으로 추가했습니다. 이로써 프론트에서 blackList 관리를 더 수월하게 할 수 있도록 했습니다.
- 참여자 권한이 바뀔때 요청자와, 바뀐 타깃 유저에게 소켓 메시지를 보냅니다
- 에러 메시지와 소켓으로 통신하는 메시지를 한글로 바꿨습니다.
<br><br>
- Question 커밋이 봐주세요!
<br><br>
=> 소켓으로 채팅방 상태 전송

nestjs/src/socket/home/home.gateway.ts
- #이슈번호
#219 
관리자권한 변경시 소켓이벤트
<br><br>
- targetSocket과 request socket에게만 보내주던 것을 room에 참여한 모든 참여자에게 보냄
<br><br>
<br><br>
=> [Hotfix]: 채팅 참여하고 있는 모든 참여자에게 소켓 이벤트를 보내주도록 수정

nestjs/src/chat/chat.service.ts
private 채팅방 입장시 비밀번호를 검증 안하고 있는 버그 수정
<br><br>
<br><br>
<br><br>
=> [Fix]: private채팅방 입장시 비밀번호 검증 로직 수정

nestjs/src/socket/game/enum/gameStatus.enum.ts, nestjs/src/socket/game/gameSocket.service.ts
- #234 
- pingpong 게임 타겟 스코어
<br><br>
- 게임 종료 점수 10점으로 변경
- 바 충돌 시 공 속도 변경 수치 변경
<br><br>
<br><br>
=> pingpong 게임 타겟 스코어 변경

nestjs/src/profile/profile.service.ts
- #237 
otp 설정해제 시 해제 안되는 버그
<br><br>
- 엔티티에 null로 저장하는 것으로 변경
<br><br>
<br><br>
=> otp 설정해제 시 해제 안되는 버그
